CREATE DATABASE LEAVEMANAGEMENT;
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    MANAGER_ID INT,
    DATE_OF_BIRTH DATE,
    PHONE_NUMBER INT,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE LOGIN_CREDENTIALS(
LOGIN_ID INT PRIMARY KEY AUTO_INCREMENT,
EMAILID VARCHAR(100) UNIQUE NOT NULL,
PASSWORD VARCHAR(255) NOT NULL
);
CREATE TABLE LEAVE_TYPES (
    TYPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPE_NAME VARCHAR(50) UNIQUE NOT NULL
);
USE LEAVEMANAGEMENT;
CREATE TABLE LEAVE_REQUESTS (
    LEAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_ID INT,
    LEAVE_TYPE_ID INT,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    MANAGER_ID INT,
    COMMENTS VARCHAR(255),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPES(TYPE_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
CREATE TABLE LEAVE_TABLE (
    LEAVES_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMBER_OF_LEAVES INT,
    START_DATE DATE DEFAULT '2024-04-01',
    END_DATE DATE DEFAULT '2025-03-31',
    EMPLOYEE_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

DESC EMPLOYEES;
DESC  LEAVE_REQUESTS;
DESC  LEAVE_TYPES;
DESC LOGIN_CREDENTIALS;
DESC LEAVE_TABLE;
CREATE TABLE COOKIE (
    COOKIE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COOKIE_NAME VARCHAR(255) NOT NULL,
    COOKIE_VALUE VARCHAR(255) NOT NULL,
    LOGIN_ID INT,
    EXPIRY_DATE DATE,
    FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN_CREDENTIALS(LOGIN_ID)
);
SELECT * FROM LOGIN_CREDENTIALS;
INSERT INTO LOGIN_CREDENTIALS(EMAILID,PASSWORD) VALUES("roopa@gmail.com","123");
